unit Test.Forms;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, dxSkinOffice2007Green, dxSkinXmas2008Blue, cxLookAndFeels,
  dxSkinDarkSide, cxGridCustomView, dxSkinValentine, dxSkinCoffee, dxSkinSilver,
  dxSkinOffice2007Black, System.Classes, dxSkiniMaginary, cxNavigator, FireDAC.DApt,
  Vcl.Buttons, dxSkinBlueprint, FireDAC.Stan.Intf, cxCustomData, dxSkinDarkRoom,
  dxSkinSummer2008, System.Variants, dxSkinOffice2013White, FireDAC.Stan.Param,
  dxSkinsDefaultPainters, Data.DB, cxData, cxStyles, cxGridDBTableView,
  dxSkinDevExpressStyle, dxSkinSharpPlus, Ladder.Activity.Classes, dxSkinBlue,
  dxSkinOffice2013DarkGray, FireDAC.Comp.DataSet, dxSkinOffice2010Silver,
  Vcl.ExtCtrls, FireDAC.DApt.Intf, dxSkinOffice2016Colorful, cxDataStorage,
  FireDAC.Comp.Client, dxSkinOffice2013LightGray, uConSqlServer, Vcl.Mask,
  dxSkinMetropolisDark, dxSkinTheAsphaltWorld, FireDAC.Stan.Option, dxSkinSeven,
  cxGrid, dxSkinBlack, dxSkinLilian, FireDAC.Stan.Error, cxGridLevel,
  dxSkinVisualStudio2013Dark, Vcl.Graphics, Vcl.Forms, dxSkinMoneyTwins, cxEdit,
  dxSkinVisualStudio2013Light, dxSkinGlassOceans, dxSkinFoggy, dxSkinSpringTime,
  dxSkinHighContrast, dxSkinMcSkin, FireDAC.Stan.Async, dxSkinVisualStudio2013Blue,
  FireDAC.DatS, cxGraphics, cxFilter, Vcl.DBCtrls, dxSkinSevenClassic, cxClasses,
  Vcl.Grids, dxSkinLondonLiquidSky, dxSkinsCore, dxSkinPumpkin,
  dxSkinDevExpressDarkStyle, dxSkinSharp, dxSkinscxPCPainter, dxSkinOffice2007Pink,
  dxSkinMetropolis, FireDAC.Phys.Intf, Form.CadastroAtividade, Vcl.Controls,
  Vcl.StdCtrls, dxSkinStardust, cxGridCustomTableView, dxSkinCaramel, Winapi.Windows,
  cxControls, Winapi.Messages, Vcl.DBGrids, dxSkinOffice2007Blue,
  cxLookAndFeelPainters, Vcl.Dialogs, dxSkinLiquidSky, dxSkinOffice2010Blue,
  dxSkinOffice2007Silver, dxSkinWhiteprint, cxDBData, dxSkinOffice2010Black,
  System.SysUtils, dxSkinOffice2016Dark, cxGridTableView, dxSkinVS2010, Form.CadastroProcesso,
  Form.PesquisaAviso;

type
  // Test methods for class TFormCadastroAviso

  TestTFormCadastroAviso = class(TTestCase)
  strict private
    FFormPesquisaAviso: TFormPesquisaAviso;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure AbrirFormCadastroAtividade;
  end;

implementation

procedure TestTFormCadastroAviso.AbrirFormCadastroAtividade;
begin
  FFormPesquisaAviso.ShowModal;
end;

procedure TestTFormCadastroAviso.SetUp;
begin
  FFormPesquisaAviso := TFormPesquisaAviso.Create(nil);
end;

procedure TestTFormCadastroAviso.TearDown;
begin
  FFormPesquisaAviso.Free;
  FFormPesquisaAviso := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFormCadastroAviso.Suite);
end.

